# Generated by Django 4.1.1 on 2022-11-10 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AE1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='ResearchSeeds/A1')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('publish', models.BooleanField(default=True, null=True)),
                ('number', models.IntegerField(default='1')),
            ],
        ),
        migrations.CreateModel(
            name='AE4M',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('number', models.IntegerField(default=1)),
                ('publish', models.BooleanField(default=True, null=True)),
                ('lprice', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='AEGM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='0', max_length=100)),
                ('publish', models.BooleanField()),
                ('lprice', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='AEPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExNo', models.IntegerField(default=1)),
                ('semestery', models.IntegerField(default=1)),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
            options={
                'ordering': ['ExNo', 'semestery'],
            },
        ),
        migrations.CreateModel(
            name='AGMAGoldenM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='0', max_length=100)),
                ('publish', models.BooleanField()),
                ('lprice', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='AGMAPriveosS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExNo', models.IntegerField(default=1)),
                ('semestery', models.IntegerField(default=1)),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
            options={
                'ordering': ['ExNo', 'semestery'],
            },
        ),
        migrations.CreateModel(
            name='AGrammar4M',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('number', models.IntegerField(default=1)),
                ('publish', models.BooleanField(default=True, null=True)),
                ('lprice', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='AGrammer1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='GMA/AGrammer1')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('number', models.IntegerField(default=1)),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AGStatementM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='0', max_length=100)),
                ('publish', models.BooleanField()),
                ('lprice', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='AMorphology1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='GMA/AMorphology1')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('publish', models.BooleanField(default=True, null=True)),
                ('number', models.IntegerField(default='1')),
            ],
        ),
        migrations.CreateModel(
            name='AMorphology4M',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('number', models.IntegerField(default=1)),
                ('publish', models.BooleanField(default=True, null=True)),
                ('lprice', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Application1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='GMA/Application1')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='GMA/Application2')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='GMA/Application3')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='GMA/Application4')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='GMA/Application5')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationExM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='APPStatementS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExNo', models.IntegerField(default=1)),
                ('semestery', models.IntegerField(default=1)),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
            options={
                'ordering': ['ExNo', 'semestery'],
            },
        ),
        migrations.CreateModel(
            name='APre_IslamicLiterature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='Pre_IslamicLiterature/A')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('number', models.IntegerField(default='1')),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='APStatement1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='GMA/AMorphology1')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('publish', models.BooleanField(default=True, null=True)),
                ('number', models.IntegerField(default='1')),
            ],
        ),
        migrations.CreateModel(
            name='APStatement4M',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('number', models.IntegerField(default=1)),
                ('publish', models.BooleanField(default=True, null=True)),
                ('lprice', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='AResearchSeeds1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='ResearchSeeds/A1')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('publish', models.BooleanField(default=True, null=True)),
                ('number', models.IntegerField(default='1')),
            ],
        ),
        migrations.CreateModel(
            name='AResearchSeeds4M',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('number', models.IntegerField(default=1)),
                ('publish', models.BooleanField(default=True, null=True)),
                ('lprice', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='AResearchSeedsGM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='0', max_length=100)),
                ('publish', models.BooleanField()),
                ('lprice', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='AResearchSeedsPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExNo', models.IntegerField(default=1)),
                ('semestery', models.IntegerField(default=1)),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
            options={
                'ordering': ['ExNo', 'semestery'],
            },
        ),
        migrations.CreateModel(
            name='ATH1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='ResearchSeeds/A1')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('publish', models.BooleanField(default=True, null=True)),
                ('number', models.IntegerField(default='1')),
            ],
        ),
        migrations.CreateModel(
            name='ATH4M',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('number', models.IntegerField(default=1)),
                ('publish', models.BooleanField(default=True, null=True)),
                ('lprice', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='ATHGM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='0', max_length=100)),
                ('publish', models.BooleanField()),
                ('lprice', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ATHPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExNo', models.IntegerField(default=1)),
                ('semestery', models.IntegerField(default=1)),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
            options={
                'ordering': ['ExNo', 'semestery'],
            },
        ),
        migrations.CreateModel(
            name='ATStatement1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='GMA/AMorphology1')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('publish', models.BooleanField(default=True, null=True)),
                ('number', models.IntegerField(default='1')),
            ],
        ),
        migrations.CreateModel(
            name='ATStatement4M',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('number', models.IntegerField(default=1)),
                ('publish', models.BooleanField(default=True, null=True)),
                ('lprice', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='FirstYearsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='History/GHistory')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HPre_IslamicLiterature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(default='', null=True, upload_to='Pre_IslamicLiterature/A')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('number', models.IntegerField(default='1')),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pyear', models.IntegerField(default=0)),
                ('lfile', models.FileField(upload_to='History/PHistory')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('number', models.IntegerField(default='1')),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
            options={
                'ordering': ['pyear', 'number'],
            },
        ),
        migrations.CreateModel(
            name='PPre_IslamicLiterature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(null=True, upload_to='Pre_IslamicLiterature/P')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('number', models.IntegerField(default='1')),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WGMAGlden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='GMA/WGMAGlden')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WGMAPriveos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pyear', models.IntegerField(default=0)),
                ('lfile', models.FileField(upload_to='GMA/WGMAPriveos')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('number', models.IntegerField(default='1')),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
            options={
                'ordering': ['pyear', 'number'],
            },
        ),
        migrations.CreateModel(
            name='WGrammar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='GMA/WGrammar')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('number', models.IntegerField(default='1')),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WGStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='GMA/WGMAGlden')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='History/WHistory')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('number', models.IntegerField(default='1')),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WMorphology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='GMA/WMorphology')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('publish', models.BooleanField(default=True, null=True)),
                ('number', models.IntegerField(default='1')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='WPPStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pyear', models.IntegerField(default=0)),
                ('lfile', models.FileField(upload_to='GMA/WGMAPriveos')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('number', models.IntegerField(default='1')),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
            options={
                'ordering': ['pyear', 'number'],
            },
        ),
        migrations.CreateModel(
            name='WPStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='GMA/WGrammar')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('number', models.IntegerField(default='1')),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WResearchSeedsG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='ResearchSeeds/G')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('publish', models.BooleanField(default=True, null=True)),
                ('number', models.IntegerField(default='1')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='WResearchSeedsL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='ResearchSeeds/L')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('publish', models.BooleanField(default=True, null=True)),
                ('number', models.IntegerField(default='1')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='WResearchSeedsP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='ResearchSeeds/P')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('publish', models.BooleanField(default=True, null=True)),
                ('number', models.IntegerField(default='1')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='WTStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='GMA/WGrammar')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('number', models.IntegerField(default='1')),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WMorphologyConnent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WG', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstyear.wmorphology')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.student')),
            ],
        ),
        migrations.CreateModel(
            name='WGrammarConnent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WG', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstyear.wgrammar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.student')),
            ],
        ),
        migrations.CreateModel(
            name='ATStatement4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
                ('ExNo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firstyear.atstatement4m')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='ATHP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
                ('PreviosS', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firstyear.athps')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='ATHG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
                ('ExNo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firstyear.athgm')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='ATH4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
                ('ExNo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firstyear.ath4m')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='AResearchSeedsP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
                ('PreviosS', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firstyear.aresearchseedsps')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='AResearchSeedsG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
                ('ExNo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firstyear.aresearchseedsgm')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='AResearchSeeds4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
                ('ExNo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firstyear.aresearchseeds4m')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='APStatement4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
                ('ExNo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firstyear.apstatement4m')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='APPStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
                ('PreviosS', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firstyear.appstatements')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationEx6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1, unique=True)),
                ('ExNo', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='firstyear.applicationexm')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationEx5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1, unique=True)),
                ('ExNo', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='firstyear.applicationexm')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationEx4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1, unique=True)),
                ('ExNo', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='firstyear.applicationexm')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationEx3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1, unique=True)),
                ('ExNo', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='firstyear.applicationexm')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationEx2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1, unique=True)),
                ('ExNo', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='firstyear.applicationexm')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationEx1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1, unique=True)),
                ('ExNo', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='firstyear.applicationexm')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='AMorphology4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
                ('ExNo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firstyear.amorphology4m')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='AGStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
                ('ExNo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firstyear.agmagoldenm')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='AGrammer4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
                ('ExNo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firstyear.agrammar4m')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='AGMAPriveos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
                ('PreviosS', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firstyear.agmapriveoss')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='AGMAGolden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
                ('ExNo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firstyear.agmagoldenm')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='AEP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
                ('PreviosS', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firstyear.aeps')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='AEG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
                ('ExNo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firstyear.aegm')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='AE4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
                ('ExNo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firstyear.ae4m')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
