# Generated by Django 4.1.1 on 2022-10-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstyear', '0002_wgrammar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wgrammar',
            options={'verbose_name': 'محاضرات نحو 1'},
        ),
        migrations.AddField(
            model_name='wgrammar',
            name='lprice',
            field=models.IntegerField(default=0),
        ),
    ]
