# Generated by Django 4.1.1 on 2022-10-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstyear', '0003_alter_wgrammar_options_wgrammar_lprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='wgrammar',
            name='number',
            field=models.IntegerField(default='1'),
        ),
    ]
