# Generated by Django 4.1.1 on 2022-10-07 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstyear', '0004_wgrammar_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wgrammar',
            options={'ordering': ['number'], 'verbose_name': 'محاضرات نحو 1'},
        ),
    ]
