# Generated by Django 4.1.1 on 2022-10-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstyear', '0005_alter_wgrammar_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='WMorphology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='GMA/WMorphology')),
                ('lprice', models.IntegerField(default=0)),
                ('number', models.IntegerField(default='1')),
            ],
            options={
                'verbose_name': 'محاضرات صرف 1',
                'ordering': ['number'],
            },
        ),
    ]
