# Generated by Django 4.1.1 on 2022-10-07 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstyear', '0007_gmaglden'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GMAGlden',
            new_name='WGMAGlden',
        ),
        migrations.AlterModelOptions(
            name='wgmaglden',
            options={'verbose_name': 'نحو و صرف 1 اسئلة ذهبية'},
        ),
    ]
