# Generated by Django 4.1.1 on 2022-10-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstyear', '0009_wgmapriveos'),
    ]

    operations = [
        migrations.CreateModel(
            name='AGrammer4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'نحو و صرف 1 اسئلة دورات',
                'ordering': ['number'],
            },
        ),
        migrations.AlterModelOptions(
            name='wgmaglden',
            options={'verbose_name': 'نحو و صرف 1 اسئلة ذهبية تحرير'},
        ),
        migrations.AlterModelOptions(
            name='wgmapriveos',
            options={'ordering': ['number'], 'verbose_name': 'نحو و صرف 1 اسئلة دورات تحريري'},
        ),
    ]
