# Generated by Django 4.1.1 on 2022-10-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstyear', '0011_agrammer1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agrammer4',
            options={'ordering': ['number'], 'verbose_name': 'نحو 1 سؤال و أربع خيارات'},
        ),
        migrations.RenameField(
            model_name='agrammer4',
            old_name='true',
            new_name='No_true',
        ),
        migrations.AddField(
            model_name='agrammer4',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
