# Generated by Django 4.1.1 on 2022-10-08 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstyear', '0012_alter_agrammer4_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agrammer1',
            name='lfile',
            field=models.FileField(upload_to='GMA/AGrammer1'),
        ),
        migrations.AlterField(
            model_name='wgmaglden',
            name='lfile',
            field=models.FileField(upload_to='GMA/WGMAGlden'),
        ),
        migrations.AlterField(
            model_name='wgmapriveos',
            name='lfile',
            field=models.FileField(upload_to='GMA/WGMAPriveos'),
        ),
    ]
