# Generated by Django 4.1.1 on 2022-10-08 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstyear', '0013_alter_agrammer1_lfile_alter_wgmaglden_lfile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMorphology1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='GMA/AMorphology1')),
                ('lprice', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'صرف 1 سؤال و جواب',
            },
        ),
        migrations.AlterModelOptions(
            name='agrammer1',
            options={'verbose_name': 'نحو 1 سؤال و جواب'},
        ),
    ]
