# Generated by Django 4.1.1 on 2022-10-08 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstyear', '0014_amorphology1_alter_agrammer1_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMorphology4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'صرف 1 سؤال و أربع خيارات',
                'ordering': ['number'],
            },
        ),
    ]
