# Generated by Django 4.1.1 on 2022-10-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstyear', '0016_agmagolden'),
    ]

    operations = [
        migrations.CreateModel(
            name='AGMAPriveos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'نحو و صرف 1 مؤتمت اسئلة دورات',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Application1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='GMA/AMorphology1')),
                ('lprice', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'تطبيق اسلوب الشرط',
            },
        ),
        migrations.CreateModel(
            name='Application2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='GMA/AMorphology1')),
                ('lprice', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'إعراب جمل',
            },
        ),
        migrations.CreateModel(
            name='Application3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='GMA/AMorphology1')),
                ('lprice', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'المصادر المؤولة',
            },
        ),
        migrations.CreateModel(
            name='Application4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='GMA/AMorphology1')),
                ('lprice', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'أسلوب النداء',
            },
        ),
        migrations.CreateModel(
            name='Application5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='GMA/AMorphology1')),
                ('lprice', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'ثوابت إعرابية',
            },
        ),
    ]
