# Generated by Django 4.1.1 on 2022-10-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstyear', '0017_agmapriveos_application1_application2_application3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationEx1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'اختبار 1',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationEx2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'اختبار 2',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationEx3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'اختبار 3',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationEx4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'اختبار 4',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationEx5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'اختبار 5',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationEx6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'اختبار 6',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationEx7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'اختبار 7',
                'ordering': ['number'],
            },
        ),
        migrations.AlterField(
            model_name='application1',
            name='lfile',
            field=models.FileField(upload_to='GMA/Application1'),
        ),
        migrations.AlterField(
            model_name='application2',
            name='lfile',
            field=models.FileField(upload_to='GMA/Application2'),
        ),
        migrations.AlterField(
            model_name='application3',
            name='lfile',
            field=models.FileField(upload_to='GMA/Application3'),
        ),
        migrations.AlterField(
            model_name='application4',
            name='lfile',
            field=models.FileField(upload_to='GMA/Application4'),
        ),
        migrations.AlterField(
            model_name='application5',
            name='lfile',
            field=models.FileField(upload_to='GMA/Application5'),
        ),
    ]
