# Generated by Django 4.1.1 on 2022-10-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstyear', '0018_applicationex1_applicationex2_applicationex3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WResearchSeedsL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='ResearchSeeds/L')),
                ('lprice', models.IntegerField(default=0)),
                ('number', models.IntegerField(default='1')),
            ],
            options={
                'verbose_name': 'محاضرات اصول البحث',
                'ordering': ['number'],
            },
        ),
    ]
