# Generated by Django 4.1.1 on 2022-10-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstyear', '0019_wresearchseedsl'),
    ]

    operations = [
        migrations.CreateModel(
            name='WResearchSeedsG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='ResearchSeeds/L')),
                ('lprice', models.IntegerField(default=0)),
                ('number', models.IntegerField(default='1')),
            ],
            options={
                'verbose_name': 'اسئلة ذهبية اصول البحث',
                'ordering': ['number'],
            },
        ),
        migrations.AlterField(
            model_name='wgrammar',
            name='lfile',
            field=models.FileField(upload_to='GMA/WGrammar'),
        ),
    ]
