# Generated by Django 4.1.1 on 2022-10-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstyear', '0021_wresearchseedsp_alter_wresearchseedsg_lfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AResearchSeeds1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='GMA/Application5')),
                ('lprice', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'ثوابت إعرابية',
            },
        ),
    ]
