# Generated by Django 4.1.1 on 2022-10-09 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstyear', '0022_aresearchseeds1'),
    ]

    operations = [
        migrations.AddField(
            model_name='wgrammar',
            name='publish',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='aresearchseeds1',
            name='lfile',
            field=models.FileField(upload_to='ResearchSeeds/A1'),
        ),
    ]
