# Generated by Django 4.1.1 on 2022-10-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstyear', '0025_alter_agmagolden_lprice_alter_agmapriveos_lprice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AresearchSeeds4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
            options={
                'verbose_name': 'اصول البحث سؤال و أربع خيارات',
                'ordering': ['number'],
            },
        ),
        migrations.AlterField(
            model_name='agmagolden',
            name='publish',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='agmapriveos',
            name='publish',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='agrammer1',
            name='publish',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='agrammer4',
            name='publish',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='amorphology1',
            name='publish',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='amorphology4',
            name='publish',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='application1',
            name='publish',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='application2',
            name='publish',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='application3',
            name='publish',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='application4',
            name='publish',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='application5',
            name='publish',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationex1',
            name='publish',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationex2',
            name='publish',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationex3',
            name='publish',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationex4',
            name='publish',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationex5',
            name='publish',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationex6',
            name='publish',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationex7',
            name='publish',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='aresearchseeds1',
            name='publish',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='wgmaglden',
            name='publish',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='wgmapriveos',
            name='publish',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='wgrammar',
            name='publish',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='wmorphology',
            name='publish',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='wresearchseedsg',
            name='publish',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='wresearchseedsl',
            name='publish',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='wresearchseedsp',
            name='publish',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
