# Generated by Django 4.1.1 on 2022-10-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstyear', '0026_aresearchseeds4_alter_agmagolden_publish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agrammer4',
            name='lprice',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
