# Generated by Django 4.1.1 on 2022-10-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstyear', '0027_alter_agrammer4_lprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='AResearchSeedsG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
            options={
                'verbose_name': 'اصول البحث سؤال و أربع خيارات',
                'ordering': ['number'],
            },
        ),
    ]
