# Generated by Django 4.1.1 on 2022-10-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstyear', '0028_aresearchseedsg'),
    ]

    operations = [
        migrations.CreateModel(
            name='AResearchSeedsP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.AlterModelOptions(
            name='agmagolden',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='agmapriveos',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='agrammer1',
            options={},
        ),
        migrations.AlterModelOptions(
            name='agrammer4',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='amorphology1',
            options={},
        ),
        migrations.AlterModelOptions(
            name='amorphology4',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='application1',
            options={},
        ),
        migrations.AlterModelOptions(
            name='application2',
            options={},
        ),
        migrations.AlterModelOptions(
            name='application3',
            options={},
        ),
        migrations.AlterModelOptions(
            name='application4',
            options={},
        ),
        migrations.AlterModelOptions(
            name='application5',
            options={},
        ),
        migrations.AlterModelOptions(
            name='applicationex1',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='applicationex2',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='applicationex3',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='applicationex4',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='applicationex5',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='applicationex6',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='applicationex7',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='aresearchseeds1',
            options={},
        ),
        migrations.AlterModelOptions(
            name='aresearchseeds4',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='aresearchseedsg',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='firstyearsuser',
            options={},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={},
        ),
        migrations.AlterModelOptions(
            name='wgmaglden',
            options={},
        ),
        migrations.AlterModelOptions(
            name='wgmapriveos',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='wgrammar',
            options={},
        ),
        migrations.AlterModelOptions(
            name='wmorphology',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='wresearchseedsg',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='wresearchseedsl',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='wresearchseedsp',
            options={'ordering': ['number']},
        ),
    ]
