# Generated by Django 4.1.1 on 2022-10-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstyear', '0029_aresearchseedsp_alter_agmagolden_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aresearchseedsp',
            name='ExNo',
            field=models.IntegerField(default=1),
        ),
    ]
