# Generated by Django 4.1.1 on 2022-10-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstyear', '0030_aresearchseedsp_exno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicationEx7',
        ),
        migrations.AddField(
            model_name='agmagolden',
            name='ExNo',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='agmapriveos',
            name='ExNo',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='agrammer1',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='agrammer4',
            name='ExNo',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='amorphology1',
            name='number',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='amorphology4',
            name='ExNo',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='aresearchseeds1',
            name='number',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='aresearchseeds4',
            name='ExNo',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='aresearchseedsg',
            name='ExNo',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='wgmaglden',
            name='number',
            field=models.IntegerField(default='1'),
        ),
    ]
