# Generated by Django 4.1.1 on 2022-10-09 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstyear', '0031_delete_applicationex7_agmagolden_exno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wgmaglden',
            name='number',
        ),
    ]
