# Generated by Django 4.1.1 on 2022-10-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstyear', '0033_agmapriveoss_remove_agmagolden_exno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agmapriveos',
            name='lprice',
        ),
        migrations.RemoveField(
            model_name='agmapriveos',
            name='publish',
        ),
        migrations.AddField(
            model_name='agmapriveoss',
            name='lprice',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='agmapriveoss',
            name='publish',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
