# Generated by Django 4.1.1 on 2022-10-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstyear', '0034_remove_agmapriveos_lprice_remove_agmapriveos_publish_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agmapriveoss',
            options={'ordering': ['ExNo', 'semestery']},
        ),
        migrations.RemoveField(
            model_name='wgmapriveos',
            name='lname',
        ),
        migrations.AddField(
            model_name='wgmapriveos',
            name='pyear',
            field=models.IntegerField(default=0),
        ),
    ]
