# Generated by Django 4.1.1 on 2022-10-12 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstyear', '0035_alter_agmapriveoss_options_remove_wgmapriveos_lname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AGrammar4M',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('number', models.IntegerField(default=1)),
                ('publish', models.BooleanField(default=True, null=True)),
                ('lprice', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='wgmapriveos',
            options={'ordering': ['pyear', 'number']},
        ),
        migrations.RemoveField(
            model_name='agrammer4',
            name='lprice',
        ),
        migrations.RemoveField(
            model_name='agrammer4',
            name='publish',
        ),
        migrations.AlterField(
            model_name='agrammer4',
            name='ExNo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firstyear.agrammar4m'),
        ),
    ]
