# Generated by Django 4.1.1 on 2022-10-12 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstyear', '0036_agrammar4m_alter_wgmapriveos_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMorphology4M',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('number', models.IntegerField(default=1)),
                ('publish', models.BooleanField(default=True, null=True)),
                ('lprice', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='amorphology4',
            name='lprice',
        ),
        migrations.RemoveField(
            model_name='amorphology4',
            name='publish',
        ),
        migrations.AlterField(
            model_name='amorphology4',
            name='ExNo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firstyear.amorphology4m'),
        ),
    ]
