# Generated by Django 4.1.1 on 2022-10-13 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstyear', '0037_amorphology4m_remove_amorphology4_lprice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AGMAGoldenM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('publish', models.BooleanField()),
                ('lprice', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='agmagolden',
            name='lprice',
        ),
        migrations.RemoveField(
            model_name='agmagolden',
            name='publish',
        ),
        migrations.AddField(
            model_name='agmagolden',
            name='ExNo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firstyear.agmagoldenm'),
        ),
    ]
