# Generated by Django 4.1.1 on 2022-10-13 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstyear', '0038_agmagoldenm_remove_agmagolden_lprice_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amorphology4m',
            options={'ordering': ['number']},
        ),
    ]
