# Generated by Django 4.1.1 on 2022-10-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstyear', '0041_alter_agmagoldenm_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agmagoldenm',
            name='name',
            field=models.TextField(default='0', max_length=100),
        ),
    ]
