# Generated by Django 4.1.1 on 2022-10-13 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstyear', '0042_alter_agmagoldenm_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationex1',
            name='number',
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='applicationex2',
            name='number',
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='applicationex3',
            name='number',
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='applicationex4',
            name='number',
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='applicationex5',
            name='number',
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='applicationex6',
            name='number',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
