# Generated by Django 4.1.1 on 2022-10-13 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstyear', '0043_alter_applicationex1_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationExM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='applicationex1',
            name='lprice',
        ),
        migrations.RemoveField(
            model_name='applicationex1',
            name='publish',
        ),
    ]
