# Generated by Django 4.1.1 on 2022-10-13 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstyear', '0044_applicationexm_remove_applicationex1_lprice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationex2',
            name='lprice',
        ),
        migrations.RemoveField(
            model_name='applicationex2',
            name='publish',
        ),
        migrations.RemoveField(
            model_name='applicationex3',
            name='lprice',
        ),
        migrations.RemoveField(
            model_name='applicationex3',
            name='publish',
        ),
        migrations.RemoveField(
            model_name='applicationex4',
            name='lprice',
        ),
        migrations.RemoveField(
            model_name='applicationex4',
            name='publish',
        ),
        migrations.RemoveField(
            model_name='applicationex5',
            name='lprice',
        ),
        migrations.RemoveField(
            model_name='applicationex5',
            name='publish',
        ),
        migrations.RemoveField(
            model_name='applicationex6',
            name='lprice',
        ),
        migrations.RemoveField(
            model_name='applicationex6',
            name='publish',
        ),
    ]
