# Generated by Django 4.1.1 on 2022-10-14 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstyear', '0045_remove_applicationex2_lprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationex1',
            name='ExNo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='firstyear.applicationexm'),
        ),
    ]
