# Generated by Django 4.1.1 on 2022-10-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstyear', '0047_applicationex2_exno_applicationex3_exno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APre_IslamicLiterature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='Pre_IslamicLiterature/A')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('number', models.IntegerField(default='1')),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GPre_IslamicLiterature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='Pre_IslamicLiterature/G')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HPre_IslamicLiterature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='Pre_IslamicLiterature/A')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('number', models.IntegerField(default='1')),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PPre_IslamicLiterature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='Pre_IslamicLiterature/P')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('number', models.IntegerField(default='1')),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
        ),
    ]
