# Generated by Django 4.1.1 on 2022-10-31 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstyear', '0053_aresearchseeds4m_remove_aresearchseeds4_lprice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AResearchSeedsGM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='0', max_length=100)),
                ('publish', models.BooleanField()),
                ('lprice', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='AResearchSeedsPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExNo', models.IntegerField(default=1)),
                ('semestery', models.IntegerField(default=1)),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
            options={
                'ordering': ['ExNo', 'semestery'],
            },
        ),
        migrations.RemoveField(
            model_name='aresearchseedsg',
            name='lprice',
        ),
        migrations.RemoveField(
            model_name='aresearchseedsg',
            name='publish',
        ),
        migrations.RemoveField(
            model_name='aresearchseedsp',
            name='ExNo',
        ),
        migrations.RemoveField(
            model_name='aresearchseedsp',
            name='lprice',
        ),
        migrations.RemoveField(
            model_name='aresearchseedsp',
            name='publish',
        ),
        migrations.AddField(
            model_name='aresearchseedsp',
            name='PreviosS',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firstyear.aresearchseedsps'),
        ),
        migrations.AlterField(
            model_name='aresearchseedsg',
            name='ExNo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firstyear.aresearchseedsgm'),
        ),
    ]
