# Generated by Django 4.1.1 on 2022-10-31 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstyear', '0054_aresearchseedsgm_aresearchseedsps_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agrammar4m',
            options={'ordering': ['number']},
        ),
    ]
