# Generated by Django 4.1.1 on 2022-11-01 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstyear', '0055_alter_agrammar4m_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AE1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='ResearchSeeds/A1')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('publish', models.BooleanField(default=True, null=True)),
                ('number', models.IntegerField(default='1')),
            ],
        ),
        migrations.CreateModel(
            name='AE4M',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('number', models.IntegerField(default=1)),
                ('publish', models.BooleanField(default=True, null=True)),
                ('lprice', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='AEGM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='0', max_length=100)),
                ('publish', models.BooleanField()),
                ('lprice', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='AEPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExNo', models.IntegerField(default=1)),
                ('semestery', models.IntegerField(default=1)),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
            options={
                'ordering': ['ExNo', 'semestery'],
            },
        ),
        migrations.CreateModel(
            name='AEP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
                ('PreviosS', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firstyear.aeps')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='AEG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
                ('ExNo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firstyear.aegm')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='AE4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
                ('ExNo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firstyear.ae4m')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
