# Generated by Django 4.1.1 on 2022-11-01 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstyear', '0057_ath1_ath4m_athgm_athps_athp_athg_ath4'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPre_IslamicLiteratureM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='0', max_length=100)),
                ('publish', models.BooleanField()),
                ('lprice', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='gpre_islamicliterature',
            name='lfile',
        ),
        migrations.RemoveField(
            model_name='gpre_islamicliterature',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='gpre_islamicliterature',
            name='lprice',
        ),
        migrations.RemoveField(
            model_name='gpre_islamicliterature',
            name='publish',
        ),
        migrations.AddField(
            model_name='gpre_islamicliterature',
            name='No_true',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='gpre_islamicliterature',
            name='ans1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='gpre_islamicliterature',
            name='ans2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='gpre_islamicliterature',
            name='ans3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='gpre_islamicliterature',
            name='ans4',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='gpre_islamicliterature',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='gpre_islamicliterature',
            name='question',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='gpre_islamicliterature',
            name='why',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='gpre_islamicliterature',
            name='ExNo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firstyear.gpre_islamicliteraturem'),
        ),
    ]
