# Generated by Django 4.1.1 on 2022-11-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstyear', '0058_gpre_islamicliteraturem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hpre_islamicliterature',
            name='lfile',
            field=models.FileField(default='', null=True, upload_to='Pre_IslamicLiterature/A'),
        ),
        migrations.AlterField(
            model_name='ppre_islamicliterature',
            name='lfile',
            field=models.FileField(null=True, upload_to='Pre_IslamicLiterature/P'),
        ),
        migrations.DeleteModel(
            name='GPre_IslamicLiterature',
        ),
        migrations.DeleteModel(
            name='GPre_IslamicLiteratureM',
        ),
    ]
