# Generated by Django 4.1.1 on 2022-11-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstyear', '0059_alter_hpre_islamicliterature_lfile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WGStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='GMA/WGMAGlden')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WPPStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pyear', models.IntegerField(default=0)),
                ('lfile', models.FileField(upload_to='GMA/WGMAPriveos')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('number', models.IntegerField(default='1')),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
            options={
                'ordering': ['pyear', 'number'],
            },
        ),
        migrations.CreateModel(
            name='WPStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='GMA/WGrammar')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('number', models.IntegerField(default='1')),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WTStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='GMA/WGrammar')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('number', models.IntegerField(default='1')),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
        ),
    ]
