from django.contrib import admin
from .models import *
# Register your models here.
admin.site.register(AGrammer31)
admin.site.register(AGrammer34)
admin.site.register(AGrammar34M)
admin.site.register(AMorphology34)
admin.site.register(AMorphology34M)
admin.site.register(AMorphology31)
admin.site.register(AGMA3Golden)
admin.site.register(AGMA3GoldenM)
admin.site.register(AGMA3Priveos)
admin.site.register(AGMA3PriveosS)
admin.site.register(AQuranSciences)
admin.site.register(HQuranSciences)
admin.site.register(QuranSciencesG)
admin.site.register(QuranSciencesP)
admin.site.register(AIslamicLiterature)
admin.site.register(HIslamicLiterature)
admin.site.register(GIslamicLiterature)
admin.site.register(PIslamicLiterature)
admin.site.register(AE31)
admin.site.register(AE34M)
admin.site.register(AE34)
admin.site.register(AE3P)
admin.site.register(AE3PS)
admin.site.register(Maryam)
admin.site.register(AMM)
admin.site.register(Persian)