# Generated by Django 4.1.1 on 2022-11-12 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AE31',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='AE3/AE31')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('publish', models.BooleanField(default=True, null=True)),
                ('number', models.IntegerField(default='1')),
            ],
        ),
        migrations.CreateModel(
            name='AE34M',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('number', models.IntegerField(default=1)),
                ('publish', models.BooleanField(default=True, null=True)),
                ('lprice', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='AE3PS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExNo', models.IntegerField(default=1)),
                ('semestery', models.IntegerField(default=1)),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
            options={
                'ordering': ['ExNo', 'semestery'],
            },
        ),
        migrations.CreateModel(
            name='AGMA3GoldenM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='0', max_length=100)),
                ('publish', models.BooleanField()),
                ('lprice', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='AGMA3PriveosS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExNo', models.IntegerField(default=1)),
                ('semestery', models.IntegerField(default=1)),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
            options={
                'ordering': ['ExNo', 'semestery'],
            },
        ),
        migrations.CreateModel(
            name='AGrammar34M',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('number', models.IntegerField(default=1)),
                ('publish', models.BooleanField(default=True, null=True)),
                ('lprice', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AGrammer31',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='GMA3/AGrammer1')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('number', models.IntegerField(default=1)),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AGSemanticsM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='0', max_length=100)),
                ('publish', models.BooleanField()),
                ('lprice', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='AIslamicLiterature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='IslamicLiterature/AIslamicLiterature')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('number', models.IntegerField(default=1)),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AMM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='QuranSciences/AMM')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('number', models.IntegerField(default=1)),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AMorphology31',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='GMA3/AMorphology1')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('publish', models.BooleanField(default=True, null=True)),
                ('number', models.IntegerField(default='1')),
            ],
        ),
        migrations.CreateModel(
            name='AMorphology34M',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('number', models.IntegerField(default=1)),
                ('publish', models.BooleanField(default=True, null=True)),
                ('lprice', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='APPSemanticsS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExNo', models.IntegerField(default=1)),
                ('semestery', models.IntegerField(default=1)),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
            options={
                'ordering': ['ExNo', 'semestery'],
            },
        ),
        migrations.CreateModel(
            name='APSemantics1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='Semantics/APSemantics1')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('publish', models.BooleanField(default=True, null=True)),
                ('number', models.IntegerField(default='1')),
            ],
        ),
        migrations.CreateModel(
            name='APSemantics4M',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('number', models.IntegerField(default=1)),
                ('publish', models.BooleanField(default=True, null=True)),
                ('lprice', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='AQuranSciences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='QuranSciences/AQuranSciences')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('number', models.IntegerField(default=1)),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ATSemantics1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='Semantics/ATSemantics1')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('publish', models.BooleanField(default=True, null=True)),
                ('number', models.IntegerField(default='1')),
            ],
        ),
        migrations.CreateModel(
            name='ATSemantics4M',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('number', models.IntegerField(default=1)),
                ('publish', models.BooleanField(default=True, null=True)),
                ('lprice', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='GHistory2M',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='0', max_length=100)),
                ('publish', models.BooleanField()),
                ('lprice', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='GIslamicLiterature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='IslamicLiterature/GIslamicLiterature')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GQuranSciencesM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='0', max_length=100)),
                ('publish', models.BooleanField()),
                ('lprice', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='HIslamicLiterature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='IslamicLiterature/HIslamicLiterature')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('number', models.IntegerField(default=1)),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='History21',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='Statement/APStatement1')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('publish', models.BooleanField(default=True, null=True)),
                ('number', models.IntegerField(default='1')),
            ],
        ),
        migrations.CreateModel(
            name='History24M',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('number', models.IntegerField(default=1)),
                ('publish', models.BooleanField(default=True, null=True)),
                ('lprice', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='HQuranSciences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='QuranSciences/HQuranSciences')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('number', models.IntegerField(default=1)),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Maryam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='QuranSciences/Maryam')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('number', models.IntegerField(default=1)),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='AE3/AE31')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('publish', models.BooleanField(default=True, null=True)),
                ('number', models.IntegerField(default='1')),
            ],
        ),
        migrations.CreateModel(
            name='PHistory2S',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExNo', models.IntegerField(default=1)),
                ('semestery', models.IntegerField(default=1)),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
            options={
                'ordering': ['ExNo', 'semestery'],
            },
        ),
        migrations.CreateModel(
            name='PIslamicLiterature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pyear', models.IntegerField(default=0)),
                ('lfile', models.FileField(upload_to='IslamicLiterature/PIslamicLiterature')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('number', models.IntegerField(default='1')),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
            options={
                'ordering': ['pyear', 'number'],
            },
        ),
        migrations.CreateModel(
            name='PQuranSciencesS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExNo', models.IntegerField(default=1)),
                ('semestery', models.IntegerField(default=1)),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
            options={
                'ordering': ['ExNo', 'semestery'],
            },
        ),
        migrations.CreateModel(
            name='WGSemantics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='Semantics/WGSemantics')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WPPSemantics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pyear', models.IntegerField(default=0)),
                ('lfile', models.FileField(upload_to='Semantics/WPPSemantics')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('number', models.IntegerField(default='1')),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
            options={
                'ordering': ['pyear', 'number'],
            },
        ),
        migrations.CreateModel(
            name='WPSemantics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='Semantics/WPSemantics')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('number', models.IntegerField(default='1')),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WTSemantics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='Semantics/WTSemantics')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('number', models.IntegerField(default='1')),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WTSemanticsConnent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secoundyear.wtsemantics')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.student')),
            ],
        ),
        migrations.CreateModel(
            name='WPSemanticsConnent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secoundyear.wpsemantics')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.student')),
            ],
        ),
        migrations.CreateModel(
            name='WPPSemanticsConnent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secoundyear.wppsemantics')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.student')),
            ],
        ),
        migrations.CreateModel(
            name='PQuranSciencesSConnent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secoundyear.pquransciencess')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.student')),
            ],
        ),
        migrations.CreateModel(
            name='PQuranSciences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
                ('PreviosS', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='secoundyear.pquransciencess')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='PIslamicLiteratureConnent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secoundyear.pislamicliterature')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.student')),
            ],
        ),
        migrations.CreateModel(
            name='PHistory2SConnent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secoundyear.phistory2s')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.student')),
            ],
        ),
        migrations.CreateModel(
            name='PHistory2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
                ('PreviosS', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='secoundyear.phistory2s')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='PersianConnent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secoundyear.persian')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.student')),
            ],
        ),
        migrations.CreateModel(
            name='MaryamConnent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secoundyear.maryam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.student')),
            ],
        ),
        migrations.CreateModel(
            name='HQuranSciencesConnent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secoundyear.hquransciences')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.student')),
            ],
        ),
        migrations.CreateModel(
            name='History24MConnent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secoundyear.history24m')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.student')),
            ],
        ),
        migrations.CreateModel(
            name='History24',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
                ('ExNo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='secoundyear.history24m')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='History21Connent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secoundyear.history21')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.student')),
            ],
        ),
        migrations.CreateModel(
            name='HIslamicLiteratureConnent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secoundyear.hislamicliterature')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.student')),
            ],
        ),
        migrations.CreateModel(
            name='GQuranSciences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
                ('ExNo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='secoundyear.gquransciencesm')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='GHistory2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
                ('ExNo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='secoundyear.ghistory2m')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='ATSemantics4MConnent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secoundyear.atsemantics4m')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.student')),
            ],
        ),
        migrations.CreateModel(
            name='ATSemantics4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
                ('ExNo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='secoundyear.atsemantics4m')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='ATSemantics1Connent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secoundyear.atsemantics1')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.student')),
            ],
        ),
        migrations.CreateModel(
            name='AQuranSciencesConnent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secoundyear.aquransciences')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.student')),
            ],
        ),
        migrations.CreateModel(
            name='APSemantics4MConnent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secoundyear.apsemantics4m')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.student')),
            ],
        ),
        migrations.CreateModel(
            name='APSemantics4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
                ('ExNo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='secoundyear.apsemantics4m')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='APSemantics1Connent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secoundyear.apsemantics1')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.student')),
            ],
        ),
        migrations.CreateModel(
            name='APPSemanticsSConnent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secoundyear.appsemanticss')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.student')),
            ],
        ),
        migrations.CreateModel(
            name='APPSemantics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
                ('PreviosS', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='secoundyear.appsemanticss')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='AMorphology34MConnent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secoundyear.amorphology34m')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.student')),
            ],
        ),
        migrations.CreateModel(
            name='AMorphology34',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
                ('ExNo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='secoundyear.amorphology34m')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='AMorphology31Connent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secoundyear.amorphology31')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.student')),
            ],
        ),
        migrations.CreateModel(
            name='AMMConnent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secoundyear.amm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.student')),
            ],
        ),
        migrations.CreateModel(
            name='AIslamicLiteratureConnent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secoundyear.aislamicliterature')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.student')),
            ],
        ),
        migrations.CreateModel(
            name='AGSemantics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
                ('ExNo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='secoundyear.agsemanticsm')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='AGrammer34',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
                ('ExNo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='secoundyear.agrammar34m')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='AGrammer31Connent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secoundyear.agrammer31')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.student')),
            ],
        ),
        migrations.CreateModel(
            name='AGrammar34MConnent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secoundyear.agrammar34m')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.student')),
            ],
        ),
        migrations.CreateModel(
            name='AGMA3PriveosSConnent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secoundyear.agma3priveoss')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.student')),
            ],
        ),
        migrations.CreateModel(
            name='AGMA3Priveos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
                ('PreviosS', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='secoundyear.agma3priveoss')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='AGMA3Golden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
                ('ExNo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='secoundyear.agma3goldenm')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='AE3PSConnent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secoundyear.ae3ps')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.student')),
            ],
        ),
        migrations.CreateModel(
            name='AE3P',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
                ('PreviosS', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='secoundyear.ae3ps')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='AE34MConnent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secoundyear.ae34m')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.student')),
            ],
        ),
        migrations.CreateModel(
            name='AE34',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
                ('ExNo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='secoundyear.ae34m')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='AE31Connent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secoundyear.ae31')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.student')),
            ],
        ),
    ]
