# Generated by Django 4.1.1 on 2022-11-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secoundyear', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gquransciences',
            options={},
        ),
        migrations.RemoveField(
            model_name='gquransciences',
            name='ExNo',
        ),
        migrations.RemoveField(
            model_name='gquransciences',
            name='No_true',
        ),
        migrations.RemoveField(
            model_name='gquransciences',
            name='ans1',
        ),
        migrations.RemoveField(
            model_name='gquransciences',
            name='ans2',
        ),
        migrations.RemoveField(
            model_name='gquransciences',
            name='ans3',
        ),
        migrations.RemoveField(
            model_name='gquransciences',
            name='ans4',
        ),
        migrations.RemoveField(
            model_name='gquransciences',
            name='number',
        ),
        migrations.RemoveField(
            model_name='gquransciences',
            name='question',
        ),
        migrations.RemoveField(
            model_name='gquransciences',
            name='why',
        ),
        migrations.AddField(
            model_name='gquransciences',
            name='lfile',
            field=models.FileField(default='', upload_to='QuranSciences/GQuranSciences'),
        ),
        migrations.AddField(
            model_name='gquransciences',
            name='lname',
            field=models.CharField(default='', max_length=55),
        ),
        migrations.AddField(
            model_name='gquransciences',
            name='lprice',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='gquransciences',
            name='publish',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.DeleteModel(
            name='GQuranSciencesM',
        ),
    ]
