# Generated by Django 4.1.1 on 2022-11-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secoundyear', '0002_alter_gquransciences_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuranSciencesG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='History/GHistory')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='GQuranSciences',
        ),
    ]
