# Generated by Django 4.1.1 on 2022-11-13 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
        ('secoundyear', '0003_quransciencesg_delete_gquransciences'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuranSciencesP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pyear', models.IntegerField(default=0)),
                ('lfile', models.FileField(upload_to='QuranSciences/QuranSciencesP')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('number', models.IntegerField(default='1')),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
            options={
                'ordering': ['pyear', 'number'],
            },
        ),
        migrations.CreateModel(
            name='QuranSciencesPConnent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secoundyear.quransciencesp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.student')),
            ],
        ),
        migrations.RemoveField(
            model_name='pquransciencessconnent',
            name='lecture',
        ),
        migrations.RemoveField(
            model_name='pquransciencessconnent',
            name='user',
        ),
        migrations.AlterField(
            model_name='quransciencesg',
            name='lfile',
            field=models.FileField(upload_to='QuranSciences/QuranSciencesG'),
        ),
        migrations.DeleteModel(
            name='PQuranSciences',
        ),
        migrations.DeleteModel(
            name='PQuranSciencesS',
        ),
        migrations.DeleteModel(
            name='PQuranSciencesSConnent',
        ),
    ]
