# Generated by Django 4.1.1 on 2022-11-16 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secoundyear', '0004_quransciencesp_quransciencespconnent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history21',
            name='lfile',
            field=models.FileField(upload_to='History2/History21'),
        ),
    ]
