# Generated by Django 4.1.1 on 2022-11-16 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AAbbasiPoetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='AbbasiPoetry/AAbbasiPoetry')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('number', models.IntegerField(default=1)),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AAndalusianPoetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='AndalusianPoetry/AAndalusianPoetry')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('number', models.IntegerField(default=1)),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ADohman1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='Critique/ADohman1')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('number', models.IntegerField(default=1)),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ADohman4M',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('number', models.IntegerField(default=1)),
                ('publish', models.BooleanField(default=True, null=True)),
                ('lprice', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AGMA5GoldenM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='0', max_length=100)),
                ('publish', models.BooleanField()),
                ('lprice', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='AGMA5PriveosS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExNo', models.IntegerField(default=1)),
                ('semestery', models.IntegerField(default=1)),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
            options={
                'ordering': ['ExNo', 'semestery'],
            },
        ),
        migrations.CreateModel(
            name='AGrammar54M',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('number', models.IntegerField(default=1)),
                ('publish', models.BooleanField(default=True, null=True)),
                ('lprice', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AGrammer51',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='GMA5/AGrammer1')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('number', models.IntegerField(default=1)),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AMorphology51',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='GMA5/AMorphology1')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('publish', models.BooleanField(default=True, null=True)),
                ('number', models.IntegerField(default='1')),
            ],
        ),
        migrations.CreateModel(
            name='AMorphology54M',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('number', models.IntegerField(default=1)),
                ('publish', models.BooleanField(default=True, null=True)),
                ('lprice', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='ANawal1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='Critique/ANawal1')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('publish', models.BooleanField(default=True, null=True)),
                ('number', models.IntegerField(default='1')),
            ],
        ),
        migrations.CreateModel(
            name='ANawal4M',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('number', models.IntegerField(default=1)),
                ('publish', models.BooleanField(default=True, null=True)),
                ('lprice', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='APhilology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='Philology/APhilology')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('number', models.IntegerField(default=1)),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GAbbasiPoetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='AbbasiPoetry/GAbbasiPoetry')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GAndalusianPoetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='AndalusianPoetry/GAndalusianPoetry')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GCritiqueM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='0', max_length=100)),
                ('publish', models.BooleanField()),
                ('lprice', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='GHistory3M',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='0', max_length=100)),
                ('publish', models.BooleanField()),
                ('lprice', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='GPhilology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='Philology/GPhilology')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HAbbasiPoetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='AbbasiPoetry/HAbbasiPoetry')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('number', models.IntegerField(default=1)),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HAndalusianPoetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='AndalusianPoetry/HAndalusianPoetry')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('number', models.IntegerField(default=1)),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='History31',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='History3/History31')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('publish', models.BooleanField(default=True, null=True)),
                ('number', models.IntegerField(default='1')),
            ],
        ),
        migrations.CreateModel(
            name='History34M',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('number', models.IntegerField(default=1)),
                ('publish', models.BooleanField(default=True, null=True)),
                ('lprice', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='HPhilology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=55)),
                ('lfile', models.FileField(upload_to='Philology/HPhilology')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('number', models.IntegerField(default=1)),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PAbbasiPoetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pyear', models.IntegerField(default=0)),
                ('lfile', models.FileField(upload_to='AbbasiPoetry/PAbbasiPoetry')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('number', models.IntegerField(default='1')),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
            options={
                'ordering': ['pyear', 'number'],
            },
        ),
        migrations.CreateModel(
            name='PAndalusianPoetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pyear', models.IntegerField(default=0)),
                ('lfile', models.FileField(upload_to='AndalusianPoetry/PAndalusianPoetry')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('number', models.IntegerField(default='1')),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
            options={
                'ordering': ['pyear', 'number'],
            },
        ),
        migrations.CreateModel(
            name='PCritiqueS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExNo', models.IntegerField(default=1)),
                ('semestery', models.IntegerField(default=1)),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
            options={
                'ordering': ['ExNo', 'semestery'],
            },
        ),
        migrations.CreateModel(
            name='PHistory3S',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExNo', models.IntegerField(default=1)),
                ('semestery', models.IntegerField(default=1)),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
            options={
                'ordering': ['ExNo', 'semestery'],
            },
        ),
        migrations.CreateModel(
            name='PPhilology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pyear', models.IntegerField(default=0)),
                ('lfile', models.FileField(upload_to='Philology/PPhilology')),
                ('lprice', models.IntegerField(blank=True, default=0, null=True)),
                ('number', models.IntegerField(default='1')),
                ('publish', models.BooleanField(default=True, null=True)),
            ],
            options={
                'ordering': ['pyear', 'number'],
            },
        ),
        migrations.CreateModel(
            name='PPhilologyConnent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thirdyear.pphilology')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.student')),
            ],
        ),
        migrations.CreateModel(
            name='PHistory3SConnent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thirdyear.phistory3s')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.student')),
            ],
        ),
        migrations.CreateModel(
            name='PHistory3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
                ('PreviosS', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='thirdyear.phistory3s')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='PCritiqueSConnent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thirdyear.pcritiques')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.student')),
            ],
        ),
        migrations.CreateModel(
            name='PCritique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
                ('PreviosS', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='thirdyear.pcritiques')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='PAndalusianPoetryConnent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thirdyear.pandalusianpoetry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.student')),
            ],
        ),
        migrations.CreateModel(
            name='PAbbasiPoetryConnent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thirdyear.pabbasipoetry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.student')),
            ],
        ),
        migrations.CreateModel(
            name='HPhilologyConnent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thirdyear.hphilology')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.student')),
            ],
        ),
        migrations.CreateModel(
            name='History34MConnent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thirdyear.history34m')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.student')),
            ],
        ),
        migrations.CreateModel(
            name='History34',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
                ('ExNo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='thirdyear.history34m')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='History31Connent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thirdyear.history31')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.student')),
            ],
        ),
        migrations.CreateModel(
            name='HAndalusianPoetryConnent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thirdyear.handalusianpoetry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.student')),
            ],
        ),
        migrations.CreateModel(
            name='HAbbasiPoetryConnent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thirdyear.habbasipoetry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.student')),
            ],
        ),
        migrations.CreateModel(
            name='GHistory3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
                ('ExNo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='thirdyear.ghistory3m')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='GCritique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
                ('ExNo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='thirdyear.gcritiquem')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='APhilologyConnent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thirdyear.aphilology')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.student')),
            ],
        ),
        migrations.CreateModel(
            name='ANawal4MConnent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thirdyear.anawal4m')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.student')),
            ],
        ),
        migrations.CreateModel(
            name='ANawal4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans5', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
                ('ExNo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='thirdyear.anawal4m')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='ANawal1Connent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thirdyear.anawal1')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.student')),
            ],
        ),
        migrations.CreateModel(
            name='AMorphology54MConnent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thirdyear.amorphology54m')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.student')),
            ],
        ),
        migrations.CreateModel(
            name='AMorphology54',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans5', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
                ('ExNo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='thirdyear.amorphology54m')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='AMorphology51Connent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thirdyear.amorphology51')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.student')),
            ],
        ),
        migrations.CreateModel(
            name='AGrammer54',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans5', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
                ('ExNo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='thirdyear.agrammar54m')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='AGrammer51Connent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thirdyear.agrammer51')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.student')),
            ],
        ),
        migrations.CreateModel(
            name='AGrammar54MConnent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thirdyear.agrammar54m')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.student')),
            ],
        ),
        migrations.CreateModel(
            name='AGMA5PriveosSConnent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thirdyear.agma5priveoss')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.student')),
            ],
        ),
        migrations.CreateModel(
            name='AGMA5Priveos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
                ('PreviosS', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='thirdyear.agma5priveoss')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='AGMA5Golden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
                ('ExNo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='thirdyear.agma5goldenm')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='ADohmanConnent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thirdyear.adohman1')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.student')),
            ],
        ),
        migrations.CreateModel(
            name='ADohman4MConnent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thirdyear.adohman4m')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.student')),
            ],
        ),
        migrations.CreateModel(
            name='ADohman4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans5', models.TextField()),
                ('ans4', models.TextField()),
                ('why', models.TextField(default='')),
                ('No_true', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
                ('ExNo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='thirdyear.adohman4m')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='AAndalusianPoetryConnent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thirdyear.aandalusianpoetry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.student')),
            ],
        ),
        migrations.CreateModel(
            name='AAbbasiPoetryConnent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thirdyear.aabbasipoetry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.student')),
            ],
        ),
    ]
