# Generated by Django 4.1.1 on 2022-11-16 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thirdyear', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adohman4',
            old_name='ans5',
            new_name='ans3',
        ),
        migrations.RenameField(
            model_name='agrammer54',
            old_name='ans5',
            new_name='ans3',
        ),
        migrations.RenameField(
            model_name='amorphology54',
            old_name='ans5',
            new_name='ans3',
        ),
        migrations.RenameField(
            model_name='anawal4',
            old_name='ans5',
            new_name='ans3',
        ),
    ]
