from django.contrib import admin
from .models import *
# Register your models here.
admin.site.register(Users)
admin.site.register(WGrammar)
admin.site.register(WMorphology)
admin.site.register(WGMAGlden)
admin.site.register(WGMAPriveos)
admin.site.register(AGrammer1)
admin.site.register(AGrammer4)
admin.site.register(AMorphology1)
admin.site.register(AMorphology4)
admin.site.register(AMorphology4M)
admin.site.register(Application1)
admin.site.register(Application2)
admin.site.register(Application3)
admin.site.register(Application4)
admin.site.register(Application5)
admin.site.register(AGMAGolden)
admin.site.register(AGMAGoldenM)
admin.site.register(AGMAPriveos)
admin.site.register(AGMAPriveosS)
admin.site.register(AGrammar4M)
admin.site.register(WResearchSeedsL)
admin.site.register(AResearchSeeds4)
admin.site.register(AResearchSeedsG)
admin.site.register(AResearchSeedsP)
admin.site.register(ApplicationEx1)
admin.site.register(ApplicationEx2)
admin.site.register(ApplicationEx3)
admin.site.register(ApplicationEx4)
admin.site.register(ApplicationEx5)
admin.site.register(ApplicationEx6)
admin.site.register(ApplicationExM)
