from django.urls import path

from . import views
urlpatterns = [
    path('', views.login, name="login"),
    path('register/', views.register, name="register"),
    path('main/', views.main, name="main"),
    path('main/firstsemester/', views.firstsemester, name="firstsemester"),
    path('main/firstsemester/GMA', views.GMA, name="GMA"),
    path('main/firstsemester/GMA/WGMA', views.WGMA, name="WGMA"),
    path('main/firstsemester/GMA/AGMA', views.AGMA, name="AGMA"),
    path('main/firstsemester/GMA/WGMA/WGrammarM/WGrammar', views.WGrammar, name="WGrammar"),
    path('main/firstsemester/GMA/WGMA/WGrammarM/WGrammerE/<int:number>', views.WGrammerE, name="WGrammerE"),
    path('main/firstsemester/GMA/WGMA/WGrammarM', views.WGrammarM, name="WGrammarM"),
    path('main/firstsemester/GMA/WGMA/WMorphologyM', views.WMorphologyM, name="WMorphologyM"),
    path('main/firstsemester/GMA/WGMA/WMorphologyM/WMorphology', views.WMorphology, name="WMorphology"),
    path('main/firstsemester/GMA/WGMA/WMorphologyM/WMorphologyE/<int:number>', views.WMorphologyE, name="WMorphologyE"),
    path('main/firstsemester/GMA/WGMA/WGMAGoldenM', views.WGMAGoldenM, name="WGMAGoldenM"),
    path('main/firstsemester/GMA/WGMA/WGMAGoldenM/WGMAGlden', views.WGMAGlden, name="WGMAGlden"),
    path('main/firstsemester/GMA/WGMA/WGMAGoldenM/WGMAGoldenE', views.WGMAGoldenE, name="WGMAGoldenE"),
    path('main/firstsemester/GMA/WGMA/WGMAPriveosM', views.WGMAPriveosM, name="WGMAPriveosM"),
    path('main/firstsemester/GMA/WGMA/WGMAPriveosM/WGMAPriveos', views.WGMAPriveos, name="WGMAPriveos"),
    path('main/firstsemester/GMA/WGMA/WGMAPriveosM/WGMAPriveosE/<int:pyear>/<int:number>', views.WGMAPriveosE, name="WGMAPriveosE"),
    path('main/firstsemester/GMA/AGMA/AGrammar', views.AGrammer, name='AGrammar'),
    path('main/firstsemester/GMA/AGMA/AGrammar/AGrammar1M/AGrammar1', views.AGrammer1, name='AGrammar1'),
    path('main/firstsemester/GMA/AGMA/AGrammar/AGrammar1M/AGrammar1E/<int:number>', views.AGrammar1E, name='AGrammar1E'),
    path('main/firstsemester/GMA/AGMA/AGrammar/AGrammar1M', views.AGrammar1M, name='AGrammar1M'),
    path('main/firstsemester/GMA/AGMA/AGrammar/AGrammar4M', views.AGrammar4M, name='AGrammar4M'),
    path('main/firstsemester/GMA/AGMA/AGrammar/AGrammar4M/AGrammar4Add', views.AGrammar4Add, name='AGrammar4Add'),
    path('main/firstsemester/GMA/AGMA/AGrammar/AGrammar4M/AGrammar4E/<int:number>', views.AGrammar4E, name='AGrammar4E'),
    path('main/firstsemester/GMA/AGMA/AGrammar/AGrammar4M/AGrammar4/<int:number>', views.AGrammar4, name='AGrammar4'),
    path('main/firstsemester/GMA/AGMA/AMorphology', views.AMorphology, name='AMorphology'),
    path('main/firstsemester/GMA/AGMA/AMorphology/AMorphology1M/AMorphology1', views.AMorphology1, name='AMorphology1'),
    path('main/firstsemester/GMA/AGMA/AMorphology/AMorphology1M/AMorphology1E/<int:number>', views.AMorphology1E, name='AMorphology1E'),
    path('main/firstsemester/GMA/AGMA/AMorphology/AMorphology1M', views.AMorphology1M, name='AMorphology1M'),
    path('main/firstsemester/GMA/AGMA/AMorphology/AMorphology4M', views.AMorphology4M, name='AMorphology4M'),
    path('main/firstsemester/GMA/AGMA/AMorphology/AMorphology4M/AMorphology4Add', views.AMorphology4Add, name='AMorphology4Add'),
    path('main/firstsemester/GMA/AGMA/AMorphology/AMorphology4M/AMorphology4E/<int:number>', views.AMorphology4E, name='AMorphology4E'),
    path('main/firstsemester/GMA/AGMA/AMorphology/AMorphology4M/AMorphology4/<int:number>', views.AMorphology4, name='AMorphology4'),
    path('main/firstsemester/GMA/AGMA/AGMAGoldenM', views.AGMAGoldenM, name='AGMAGoldenM'),
    path('main/firstsemester/GMA/AGMA/AGMAGoldenM/AGMAGolden', views.AGMAGolden, name='AGMAGolden'),
    path('main/firstsemester/GMA/AGMA/AGMAGoldenM/AGMAGoldenAdd', views.AGMAGoldenAdd, name='AGMAGoldenAdd'),
    path('main/firstsemester/GMA/AGMA/AGMAGoldenM/AGMAGoldenE', views.AGMAGoldenE, name='AGMAGoldenE'),
    path('main/firstsemester/GMA/AGMA/AGMAPriveosS', views.AGMAPriveosS, name='AGMAPriveosS'),
    path('main/firstsemester/GMA/AGMA/AGMAPriveosS/AGMAPriveosAdd', views.AGMAPriveosAdd, name='AGMAPriveosAdd'),
    path('main/firstsemester/GMA/AGMA/AGMAPriveosS/AGMAPriveosM/<int:ExNo>/<int:semestery>', views.AGMAPriveosM, name='AGMAPriveosM'),
    path('main/firstsemester/GMA/AGMA/AGMAPriveosS/AGMAPriveos/<int:ExNo>/<int:semestery>', views.AGMAPriveos, name='AGMAPriveos'),
    path('main/firstsemester/GMA/Application', views.Application, name='Application'),
    path('main/firstsemester/GMA/Application/Application1', views.Application1, name='Application1'),
    path('main/firstsemester/GMA/Application/Application2', views.Application2, name='Application2'),
    path('main/firstsemester/GMA/Application/Application3', views.Application3, name='Application3'),
    path('main/firstsemester/GMA/Application/Application4', views.Application4, name='Application4'),
    path('main/firstsemester/GMA/Application/Application5', views.Application5, name='Application5'),
    path('main/firstsemester/GMA/Application/ApplicationEx', views.ApplicationEx, name='ApplicationEx'),
    path('main/firstsemester/GMA/Application/ApplicationEx/ApplicationEx1', views.ApplicationEx1, name='ApplicationEx1'),
    path('main/firstsemester/GMA/Application/ApplicationEx/ApplicationEx2', views.ApplicationEx2, name='ApplicationEx2'),
    path('main/firstsemester/GMA/Application/ApplicationEx/ApplicationEx3', views.ApplicationEx3, name='ApplicationEx3'),
    path('main/firstsemester/GMA/Application/ApplicationEx/ApplicationEx4', views.ApplicationEx4, name='ApplicationEx4'),
    path('main/firstsemester/GMA/Application/ApplicationEx/ApplicationEx5', views.ApplicationEx5, name='ApplicationEx5'),
    path('main/firstsemester/GMA/Application/ApplicationEx/ApplicationEx6', views.ApplicationEx6, name='ApplicationEx6'),
    path('main/firstsemester/GMA/Application/ApplicationEx/ApplicationExM/<int:id>', views.ApplicationExM, name='ApplicationExM'),
    path('main/firstsemester/ResearchSeeds', views.ResearchSeeds, name='ResearchSeeds'),
    path('main/firstsemester/ResearchSeeds/AResearchSeeds', views.AResearchSeeds, name='AResearchSeeds'),
    path('main/firstsemester/GMA/AGMA/AMorphology/AMorphology1M/AMorphology1', views.AMorphology1, name='AMorphology1'),
    path('main/firstsemester/GMA/AGMA/AMorphology/AMorphology1M/AMorphology1E/<int:number>', views.AMorphology1E, name='AMorphology1E'),
    path('main/firstsemester/GMA/AGMA/AMorphology/AMorphology1M', views.AMorphology1M, name='AMorphology1M'),
    path('main/firstsemester/ResearchSeeds/AResearchSeeds/AResearchSeeds1M/AResearchSeeds1', views.AResearchSeeds1, name='AResearchSeeds1'),
    path('main/firstsemester/ResearchSeeds/AResearchSeeds/AResearchSeeds1M/AResearchSeeds1E/<int:number>', views.AResearchSeeds1E, name='AResearchSeeds1E'),
    path('main/firstsemester/ResearchSeeds/AResearchSeeds/AResearchSeeds1M', views.AResearchSeeds1M, name='AResearchSeeds1M'),
    path('main/firstsemester/ResearchSeeds/AResearchSeeds/AResearchSeeds4M', views.AResearchSeeds4M, name='AResearchSeeds4M'),
    path('main/firstsemester/ResearchSeeds/AResearchSeeds/AResearchSeeds4M/AResearchSeeds4Add', views.AResearchSeeds4Add,name='AResearchSeeds4Add'),
    path('main/firstsemester/ResearchSeeds/AResearchSeeds/AResearchSeeds4M/AResearchSeeds4E/<int:number>', views.AResearchSeeds4E,name='AResearchSeeds4E'),
    path('main/firstsemester/ResearchSeeds/AResearchSeeds/AResearchSeeds4M/AResearchSeeds4/<int:number>', views.AResearchSeeds4,name='AResearchSeeds4'),

    path('main/firstsemester/ResearchSeeds/AResearchSeeds/AResearchSeedsGM', views.AResearchSeedsGM, name='AResearchSeedsGM'),
    path('main/firstsemester/ResearchSeeds/AResearchSeeds/AResearchSeedsGM/AResearchSeedsG', views.AResearchSeedsG, name='AResearchSeedsG'),
    path('main/firstsemester/ResearchSeeds/AResearchSeeds/AResearchSeedsGM/AResearchSeedsGE', views.AResearchSeedsGE, name='AResearchSeedsGE'),
    path('main/firstsemester/ResearchSeeds/AResearchSeeds/AResearchSeedsGM/AResearchSeedsGAdd', views.AResearchSeedsGAdd, name='AResearchSeedsGAdd'),

    path('main/firstsemester/ResearchSeeds/AResearchSeeds/AResearchSeedsPS', views.AResearchSeedsPS, name='AResearchSeedsPS'),
    path('main/firstsemester/ResearchSeeds/AResearchSeeds/AResearchSeedsPS/AResearchSeedsPAdd', views.AResearchSeedsPAdd, name='AResearchSeedsPAdd'),
    path('main/firstsemester/ResearchSeeds/AResearchSeeds/AResearchSeedsPS/AResearchSeedsPM/<int:ExNo>/<int:semestery>', views.AResearchSeedsPM, name='AResearchSeedsPM'),
    path('main/firstsemester/ResearchSeeds/AResearchSeeds/AResearchSeedsPS/AResearchSeedsP/<int:ExNo>/<int:semestery>', views.AResearchSeedsP, name='AResearchSeedsP'),

    path('main/firstsemester/E/AE', views.AEn, name='AEn'),
    path('main/firstsemester/E/AE/AEn1M/AEn1', views.AEn1, name='AEn1'),
    path('main/firstsemester/E/AE/AEn1M/AEn1E/<int:number>', views.AEn1E, name='AEn1E'),
    path('main/firstsemester/E/AE/En1M', views.AEn1M, name='AEn1M'),
    path('main/firstsemester/E/AE/AEn4M', views.AEn4M, name='AEn4M'),
    path('main/firstsemester/E/AE/AEn4M/AEn4Add', views.AEn4Add,name='AEn4Add'),
    path('main/firstsemester/E/AE/AEn4M/AEn4E/<int:number>', views.AEn4E,name='AEn4E'),
    path('main/firstsemester/E/AE/AEn4M/AEn4/<int:number>', views.AEn4,name='AEn4'),

    path('main/firstsemester/E/AE/AEnGM', views.AEnGM, name='AEnGM'),
    path('main/firstsemester/E/AE/AEnGM/AEnG', views.AEnG, name='AEnG'),
    path('main/firstsemester/E/AE/AEnGM/AEnGE', views.AEnGE, name='AEnGE'),
    path('main/firstsemester/E/AE/AEnGM/AEnGAdd', views.AEnGAdd, name='AEnGAdd'),

    path('main/firstsemester/E/AE/AEnPS', views.AEnPS, name='AEnPS'),
    path('main/firstsemester/E/AE/AEnPS/AEnPAdd', views.AEnPAdd, name='AEnPAdd'),
    path('main/firstsemester/E/AE/AEnPS/AEnPM/<int:ExNo>/<int:semestery>', views.AEnPM, name='AEnPM'),
    path('main/firstsemester/E/AE/AEnPS/AEnP/<int:ExNo>/<int:semestery>', views.AEnP, name='AEnP'),

    path('main/firstsemester/TH/ATH', views.ATh, name='ATh'),
    path('main/firstsemester/TH/ATH/ATh1M/ATh1', views.ATh1, name='ATh1'),
    path('main/firstsemester/TH/ATH/ATh1M/ATh1E/<int:number>', views.ATh1E, name='ATh1E'),
    path('main/firstsemester/TH/ATH/Th1M', views.ATh1M, name='ATh1M'),
    path('main/firstsemester/TH/ATH/ATh4M', views.ATh4M, name='ATh4M'),
    path('main/firstsemester/TH/ATH/ATh4M/ATh4Add', views.ATh4Add,name='ATh4Add'),
    path('main/firstsemester/TH/ATH/ATh4M/ATh4E/<int:number>', views.ATh4E,name='ATh4E'),
    path('main/firstsemester/TH/ATH/ATh4M/ATh4/<int:number>', views.ATh4,name='ATh4'),

    path('main/firstsemester/TH/ATH/AThGM', views.AThGM, name='AThGM'),
    path('main/firstsemester/TH/ATH/AThGM/AThG', views.AThG, name='AThG'),
    path('main/firstsemester/TH/ATH/AThGM/AThGE', views.AThGE, name='AThGE'),
    path('main/firstsemester/TH/ATH/AThGM/AThGAdd', views.AThGAdd, name='AThGAdd'),

    path('main/firstsemester/TH/ATH/AThPS', views.AThPS, name='AThPS'),
    path('main/firstsemester/TH/ATH/AThPS/AThPAdd', views.AThPAdd, name='AThPAdd'),
    path('main/firstsemester/TH/ATH/AThPS/AThPM/<int:ExNo>/<int:semestery>', views.AThPM, name='AThPM'),
    path('main/firstsemester/TH/ATH/AThPS/AThP/<int:ExNo>/<int:semestery>', views.AThP, name='AThP'),

    path('main/firstsemester/Statement', views.Statement, name='Statement'),
    path('main/firstsemester/Statement/WStatement', views.WStatement, name='WStatement'),
    path('main/firstsemester/Statement/WStatement/WPStatementM', views.WPStatementM, name='WPStatementM'),
    path('main/firstsemester/Statement/WStatement/WPStatementM/WPStatement', views.WPStatement, name='WPStatement'),
    path('main/firstsemester/Statement/WStatement/WPStatementM/WPStatement/<int:number>', views.WPStatementE, name='WPStatementE'),
    path('main/firstsemester/Statement/WStatement/WTStatementM', views.WTStatementM, name='WTStatementM'),
    path('main/firstsemester/Statement/WStatement/WTStatementM/WTStatement', views.WTStatement, name='WTStatement'),
    path('main/firstsemester/Statement/WStatement/WTStatementM/WTStatement/<int:number>', views.WTStatementE, name='WTStatementE'),
    path('main/firstsemester/Statement/WStatement/WGStatementM', views.WGStatementM, name="WGStatementM"),
    path('main/firstsemester/Statement/WStatement/WGStatementM/WGStatement', views.WGStatement, name="WGStatement"),
    path('main/firstsemester/Statement/WStatement/WGStatementM/WGStatementE', views.WGStatementE, name="WGStatementE"),
    path('main/firstsemester/Statement/WStatement/WPPStatementM', views.WPPStatementM, name="WPPStatementM"),
    path('main/firstsemester/Statement/WStatement/WPPStatementM/WPPStatement', views.WPPStatement, name="WPPStatement"),
    path('main/firstsemester/Statement/WStatement/WPPStatementM/WPPStatementE/<int:pyear>/<int:number>', views.WPPStatementE,name="WPPStatementE"),

    path('main/firstsemester/Statement/AStatement', views.AStatement, name='AStatement'),

    path('main/firstsemester/Statement/AStatement/ATStatement', views.ATStatement, name='ATStatement'),
    path('main/firstsemester/Statement/AStatement/ATStatement/ATStatement1M/ATStatement1', views.ATStatement1, name='ATStatement1'),
    path('main/firstsemester/Statement/AStatement/ATStatement/ATStatement1M/ATStatement1E/<int:number>', views.ATStatement1E,name='ATStatement1E'),
    path('main/firstsemester/Statement/AStatement/ATStatement/ATStatement1M', views.ATStatement1M, name='ATStatement1M'),

    path('main/firstsemester/Statement/AStatement/ATStatement/ATStatement4M', views.ATStatement4M, name='ATStatement4M'),
    path('main/firstsemester/Statement/AStatement/ATStatement/ATStatement4M/ATStatement4Add', views.ATStatement4Add, name='ATStatement4Add'),
    path('main/firstsemester/Statement/AStatement/ATStatement/ATStatement4M/ATStatement4E/<int:number>', views.ATStatement4E,name='ATStatement4E'),
    path('main/firstsemester/Statement/AStatement/ATStatement/ATStatement4M/ATStatement4/<int:number>', views.ATStatement4, name='ATStatement4'),

    path('main/firstsemester/Statement/AStatement/APStatement', views.APStatement, name='APStatement'),

    path('main/firstsemester/Statement/AStatement/APStatement/APStatement1M/APStatement1', views.APStatement1, name='APStatement1'),
    path('main/firstsemester/Statement/AStatement/APStatement/APStatement1M/APStatement1E/<int:number>', views.APStatement1E,name='APStatement1E'),

    path('main/firstsemester/Statement/AStatement/APStatement/APStatement1M', views.APStatement1M, name='APStatement1M'),

    path('main/firstsemester/Statement/AStatement/APStatement/APStatement4M', views.APStatement4M, name='APStatement4M'),
    path('main/firstsemester/Statement/AStatement/APStatement/APStatement4M/APStatement4Add', views.APStatement4Add,name='APStatement4Add'),
    path('main/firstsemester/Statement/AStatement/APStatement/APStatement4M/APStatement4E/<int:number>', views.APStatement4E,name='APStatement4E'),
    path('main/firstsemester/Statement/AStatement/APStatement/APStatement4M/APStatement4/<int:number>', views.APStatement4,name='APStatement4'),


    path('main/firstsemester/Statement/AStatement/AGStatementM', views.AGStatementM, name='AGStatementM'),
    path('main/firstsemester/Statement/AStatement/AGStatementM/AGStatement', views.AGStatement, name='AGStatement'),
    path('main/firstsemester/Statement/AStatement/AGStatementM/AGStatementAdd', views.AGStatementAdd, name='AGStatementAdd'),
    path('main/firstsemester/Statement/AStatement/AGStatementM/AGStatementE', views.AGStatementE, name='AGStatementE'),


    path('main/firstsemester/Statement/AStatement/APPStatementS', views.APPStatementS, name='APPStatementS'),
    path('main/firstsemester/Statement/AStatement/APPStatementS/APPStatementAdd', views.APPStatementAdd, name='APPStatementAdd'),
    path('main/firstsemester/Statement/AStatement/APPStatementS/APPStatementM/<int:ExNo>/<int:semestery>', views.APPStatementM,name='APPStatementM'),
    path('main/firstsemester/Statement/AStatement/APPStatementS/APPStatement/<int:ExNo>/<int:semestery>', views.APPStatement,name='APPStatement'),

    path('main/firstsemester/Pre_IslamicLiterature', views.Pre_IslamicLiterature, name='Pre_IslamicLiterature'),
    path('main/firstsemester/HPre_IslamicLiteratureM', views.HPre_IslamicLiteratureM, name='HPre_IslamicLiteratureM'),
    path('main/firstsemester/HPre_IslamicLiterature', views.HPre_IslamicLiterature, name='HPre_IslamicLiterature'),
    path('main/firstsemester/HPre_IslamicLiteratureE/<int:number>', views.HPre_IslamicLiteratureE, name="HPre_IslamicLiteratureE"),
    path('main/firstsemester/APre_IslamicLiteratureM', views.APre_IslamicLiteratureM, name='APre_IslamicLiteratureM'),
    path('main/firstsemester/APre_IslamicLiterature', views.APre_IslamicLiterature, name='APre_IslamicLiterature'),
    path('main/firstsemester/APre_IslamicLiteratureE/<int:number>', views.APre_IslamicLiteratureE, name="APre_IslamicLiteratureE"),


    path('main/firstsemester/History', views.History, name='History'),
    path('main/firstsemester/History/WHistoryM', views.WHistoryM, name='WHistoryM'),
    path('main/firstsemester/History/WHistoryM/WHistory', views.WHistory, name='WHistory'),
    path('main/firstsemester/History/WHistoryM/WHistoryE/<int:number>', views.WHistoryE, name='WHistoryE'),
    path('main/firstsemester/History/GHistoryM', views.WGStatementM, name="GHistoryM"),
    path('main/firstsemester/History/GHistoryM/GHistory', views.GHistory, name="GHistory"),
    path('main/firstsemester/History/GHistoryM/GHistoryE', views.GHistoryE, name="GHistoryE"),
    path('main/firstsemester/History/PHistoryS', views.PHistoryS, name="PHistoryS"),
    path('main/firstsemester/History/PHistoryS/PHistory', views.PHistory, name="PHistory"),
    path('main/firstsemester/History/PHistoryS/PHistoryE/<int:pyear>/<int:number>', views.PHistoryE,name="PHistoryE"),

]


