from django.contrib import admin
from .models import *
# Register your models here.
admin.site.register(AGrammer51)
admin.site.register(AGrammer54)
admin.site.register(AGrammar54M)
admin.site.register(AMorphology54)
admin.site.register(AMorphology54M)
admin.site.register(AMorphology51)
admin.site.register(AGMA5Golden)
admin.site.register(AGMA5GoldenM)
admin.site.register(AGMA5Priveos)
admin.site.register(AGMA5PriveosS)
admin.site.register(APhilology)
admin.site.register(HPhilology)
admin.site.register(GPhilology)
admin.site.register(PPhilology)
admin.site.register(AAbbasiPoetry)
admin.site.register(HAbbasiPoetry)
admin.site.register(GAbbasiPoetry)
admin.site.register(PAbbasiPoetry)
admin.site.register(AAndalusianPoetry)
admin.site.register(HAndalusianPoetry)
admin.site.register(GAndalusianPoetry)
admin.site.register(PAndalusianPoetry)
admin.site.register(ADohman1)
admin.site.register(ADohman4)
admin.site.register(ADohman4M)
admin.site.register(ANawal1)
admin.site.register(ANawal4)
admin.site.register(ANawal4M)
admin.site.register(GCritique)
admin.site.register(GCritiqueM)
admin.site.register(PCritique)
admin.site.register(PCritiqueS)
admin.site.register(History31)
admin.site.register(History34)
admin.site.register(History34M)
admin.site.register(GHistory3)
admin.site.register(GHistory3M)
admin.site.register(PHistory3)
admin.site.register(PHistory3S)

