from django.urls import path
from . import views
urlpatterns = [
    path('main/firstsemester/', views.firstsemester, name="firstsemester"),

    path('main/firstsemester/GMA5/GMA5', views.AGMA5, name="AGMA5"),

    path('main/firstsemester/GMA5/AGMA5/AGrammar5', views.AGrammer5, name='AGrammar5'),
    path('main/firstsemester/GMA5/AGMA5/AGrammar5/AGrammar51M/AGrammar51', views.AGrammer51, name='AGrammar51'),
    path('main/firstsemester/GMA5/AGMA5/AGrammar5/AGrammar51M/AGrammar51E/<int:number>', views.AGrammar51E,name='AGrammar51E'),
    path('main/firstsemester/GMA5/AGMA5/AGrammar5/AGrammar51M', views.AGrammar51M, name='AGrammar51M'),
    path('main/firstsemester/GMA5/AGMA5/AGrammar5/AGrammar54M', views.AGrammar54M, name='AGrammar54M'),
    path('main/firstsemester/GMA5/AGMA5/AGrammar5/AGrammar54M/AGrammar54Add', views.AGrammar54Add, name='AGrammar54Add'),
    path('main/firstsemester/GMA5/AGMA5/AGrammar5/AGrammar54M/AGrammar54E/<int:number>', views.AGrammar54E,name='AGrammar54E'),
    path('main/firstsemester/GMA5/AGMA5/AGrammar5/AGrammar54M/AGrammar54/<int:number>', views.AGrammar54,name='AGrammar54'),
    path('main/firstsemester/GMA5/AGMA5/AMorphology5', views.AMorphology5, name='AMorphology5'),
    path('main/firstsemester/GMA5/AGMA5/AMorphology5/AMorphology51M/AMorphology51', views.AMorphology51,name='AMorphology51'),
    path('main/firstsemester/GMA5/AGMA5/AMorphology5/AMorphology51M/AMorphology51E/<int:number>', views.AMorphology51E,name='AMorphology51E'),
    path('main/firstsemester/GMA5/AGMA5/AMorphology5/AMorphology51M', views.AMorphology51M, name='AMorphology51M'),
    path('main/firstsemester/GMA5/AGMA5/AMorphology5/AMorphology54M', views.AMorphology54M, name='AMorphology54M'),
    path('main/firstsemester/GMA5/AGMA5/AMorphology5/AMorphology54M/AMorphology54Add', views.AMorphology54Add,name='AMorphology54Add'),
    path('main/firstsemester/GMA5/AGMA5/AMorphology5/AMorphology54M/AMorphology54E/<int:number>', views.AMorphology54E,name='AMorphology54E'),
    path('main/firstsemester/GMA5/AGMA5/AMorphology5/AMorphology54M/AMorphology54/<int:number>', views.AMorphology54,name='AMorphology54'),
    path('main/firstsemester/GMA5/AGMA5/AGMA5GoldenM', views.AGMA5GoldenM, name='AGMA5GoldenM'),
    path('main/firstsemester/GMA5/AGMA5/AGMA5GoldenM/AGMA5Golden', views.AGMA5Golden, name='AGMA5Golden'),
    path('main/firstsemester/GMA5/AGMA5/AGMA5GoldenM/AGMA5GoldenAdd', views.AGMA5GoldenAdd, name='AGMA5GoldenAdd'),
    path('main/firstsemester/GMA5/AGMA5/AGMA5GoldenM/AGMA5GoldenE', views.AGMA5GoldenE, name='AGMA5GoldenE'),
    path('main/firstsemester/GMA5/AGMA5/AGMA5PriveosS', views.AGMA5PriveosS, name='AGMA5PriveosS'),
    path('main/firstsemester/GMA5/AGMA5/AGMA5PriveosS/AGMA5PriveosAdd', views.AGMA5PriveosAdd, name='AGMA5PriveosAdd'),
    path('main/firstsemester/GMA5/AGMA5/AGMA5PriveosS/AGMA5PriveosM/<int:ExNo>/<int:semestery>', views.AGMA5PriveosM,name='AGMA5PriveosM'),
    path('main/firstsemester/GMA5/AGMA5/AGMA5PriveosS/AGMA5Priveos/<int:ExNo>/<int:semestery>', views.AGMA5Priveos,name='AGMA5Priveos'),

    path('main/firstsemester/Philology/', views.Philology, name="Philology"),
    path('main/firstsemester/Philology/APhilologyM/APhilology', views.APhilology,name='APhilology'),
    path('main/firstsemester/Philology/APhilologyM/APhilologyE/<int:number>', views.APhilologyE,name='APhilologyE'),
    path('main/firstsemester/Philology/APhilologyM', views.APhilologyM, name='APhilologyM'),
    path('main/firstsemester/Philology/HPhilologyM/HPhilology', views.HPhilology,name='HPhilology'),
    path('main/firstsemester/Philology/HPhilologyM/HPhilologyE/<int:number>', views.HPhilologyE,name='HPhilologyE'),
    path('main/firstsemester/Philology/HPhilologyM', views.HPhilologyM, name='HPhilologyM'),
    path('main/firstsemester/Philology/PhilologyGM/PhilologyG', views.PhilologyG, name='PhilologyG'),
    path('main/firstsemester/Philology/PhilologyGM/PhilologyGE', views.PhilologyGE,name='PhilologyGE'),
    path('main/firstsemester/Philology/PhilologyGM', views.PhilologyGM, name='PhilologyGM'),
    path('main/firstsemester/Philology/PhilologyPM', views.PhilologyPM, name="PhilologyPM"),
    path('main/firstsemester/Philology/PhilologyPM/PhilologyP', views.PhilologyP, name="PhilologyP"),
    path('main/firstsemester/Philology/PhilologyPM/PhilologyPE/<int:pyear>/<int:number>', views.PhilologyPE,name="PhilologyPE"),

    path('main/firstsemester/AbbasiPoetry/', views.AbbasiPoetry, name="AbbasiPoetry"),
    path('main/firstsemester/AbbasiPoetry/AAbbasiPoetryM/AAbbasiPoetry', views.AAbbasiPoetry,name='AAbbasiPoetry'),
    path('main/firstsemester/AbbasiPoetry/AAbbasiPoetryM/AAbbasiPoetryE/<int:number>', views.AAbbasiPoetryE,name='AAbbasiPoetryE'),
    path('main/firstsemester/AbbasiPoetry/AAbbasiPoetryM', views.AAbbasiPoetryM, name='AAbbasiPoetryM'),
    path('main/firstsemester/AbbasiPoetry/HAbbasiPoetryM/HAbbasiPoetry', views.HAbbasiPoetry,name='HAbbasiPoetry'),
    path('main/firstsemester/AbbasiPoetry/HAbbasiPoetryM/HAbbasiPoetryE/<int:number>', views.HAbbasiPoetryE,name='HAbbasiPoetryE'),
    path('main/firstsemester/AbbasiPoetry/HAbbasiPoetryM', views.HAbbasiPoetryM, name='HAbbasiPoetryM'),
    path('main/firstsemester/AbbasiPoetry/AbbasiPoetryGM/AbbasiPoetryG', views.AbbasiPoetryG, name='AbbasiPoetryG'),
    path('main/firstsemester/AbbasiPoetry/AbbasiPoetryGM/AbbasiPoetryGE', views.AbbasiPoetryGE,name='AbbasiPoetryGE'),
    path('main/firstsemester/AbbasiPoetry/AbbasiPoetryGM', views.AbbasiPoetryGM, name='AbbasiPoetryGM'),
    path('main/firstsemester/AbbasiPoetry/AbbasiPoetryPM', views.AbbasiPoetryPM, name="AbbasiPoetryPM"),
    path('main/firstsemester/AbbasiPoetry/AbbasiPoetryPM/AbbasiPoetryP', views.AbbasiPoetryP, name="AbbasiPoetryP"),
    path('main/firstsemester/AbbasiPoetry/AbbasiPoetryPM/AbbasiPoetryPE/<int:pyear>/<int:number>', views.AbbasiPoetryPE,name="AbbasiPoetryPE"),
    
    path('main/firstsemester/AndalusianPoetry/', views.AndalusianPoetry, name="AndalusianPoetry"),
    path('main/firstsemester/AndalusianPoetry/AAndalusianPoetryM/AAndalusianPoetry', views.AAndalusianPoetry,name='AAndalusianPoetry'),
    path('main/firstsemester/AndalusianPoetry/AAndalusianPoetryM/AAndalusianPoetryE/<int:number>', views.AAndalusianPoetryE,name='AAndalusianPoetryE'),
    path('main/firstsemester/AndalusianPoetry/AAndalusianPoetryM', views.AAndalusianPoetryM, name='AAndalusianPoetryM'),
    path('main/firstsemester/AndalusianPoetry/HAndalusianPoetryM/HAndalusianPoetry', views.HAndalusianPoetry,name='HAndalusianPoetry'),
    path('main/firstsemester/AndalusianPoetry/HAndalusianPoetryM/HAndalusianPoetryE/<int:number>', views.HAndalusianPoetryE,name='HAndalusianPoetryE'),
    path('main/firstsemester/AndalusianPoetry/HAndalusianPoetryM', views.HAndalusianPoetryM, name='HAndalusianPoetryM'),
    path('main/firstsemester/AndalusianPoetry/AndalusianPoetryGM/AndalusianPoetryG', views.AndalusianPoetryG, name='AndalusianPoetryG'),
    path('main/firstsemester/AndalusianPoetry/AndalusianPoetryGM/AndalusianPoetryGE', views.AndalusianPoetryGE,name='AndalusianPoetryGE'),
    path('main/firstsemester/AndalusianPoetry/AndalusianPoetryGM', views.AndalusianPoetryGM, name='AndalusianPoetryGM'),
    path('main/firstsemester/AndalusianPoetry/AndalusianPoetryPM', views.AndalusianPoetryPM, name="AndalusianPoetryPM"),
    path('main/firstsemester/AndalusianPoetry/AndalusianPoetryPM/AndalusianPoetryP', views.AndalusianPoetryP, name="AndalusianPoetryP"),
    path('main/firstsemester/AndalusianPoetry/AndalusianPoetryPM/AndalusianPoetryPE/<int:pyear>/<int:number>', views.AndalusianPoetryPE,name="AndalusianPoetryPE"),

    path('main/firstsemester/Critique/Critique', views.Critique, name="Critique"),
    path('main/firstsemester/Critique/ACritique/ADohman', views.ADohman, name='ADohman'),
    path('main/firstsemester/Critique/ACritique/ADohman/ADohman1M/ADohman1', views.ADohman1, name='ADohman1'),
    path('main/firstsemester/Critique/ACritique/ADohman/ADohman1M/ADohman1E/<int:number>', views.ADohman1E,name='ADohman1E'),
    path('main/firstsemester/Critique/ACritique/ADohman/ADohman1M', views.ADohman1M, name='ADohman1M'),
    path('main/firstsemester/Critique/ACritique/ADohman/ADohman4M', views.ADohman4M, name='ADohman4M'),
    path('main/firstsemester/Critique/ACritique/ADohman/ADohman4M/ADohman4Add', views.ADohman4Add, name='ADohman4Add'),
    path('main/firstsemester/Critique/ACritique/ADohman/ADohman4M/ADohman4E/<int:number>', views.ADohman4E,name='ADohman4E'),
    path('main/firstsemester/Critique/ACritique/ADohman/ADohman4M/ADohman4/<int:number>', views.ADohman4,name='ADohman4'),
    path('main/firstsemester/Critique/ACritique/ANawal', views.ANawal, name='ANawal'),
    path('main/firstsemester/Critique/ACritique/ANawal/ANawal1M/ANawal1', views.ANawal1,name='ANawal1'),
    path('main/firstsemester/Critique/ACritique/ANawal/ANawal1M/ANawal1E/<int:number>', views.ANawal1E,name='ANawal1E'),
    path('main/firstsemester/Critique/ACritique/ANawal/ANawal1M', views.ANawal1M, name='ANawal1M'),
    path('main/firstsemester/Critique/ACritique/ANawal/ANawal4M', views.ANawal4M, name='ANawal4M'),
    path('main/firstsemester/Critique/ACritique/ANawal/ANawal4M/ANawal4Add', views.ANawal4Add,name='ANawal4Add'),
    path('main/firstsemester/Critique/ACritique/ANawal/ANawal4M/ANawal4E/<int:number>', views.ANawal4E,name='ANawal4E'),
    path('main/firstsemester/Critique/ACritique/ANawal/ANawal4M/ANawal4/<int:number>', views.ANawal4,name='ANawal4'),
    path('main/firstsemester/Critique/ACritique/CritiqueGoldenM', views.CritiqueGoldenM, name='CritiqueGoldenM'),
    path('main/firstsemester/Critique/ACritique/CritiqueGoldenM/CritiqueGolden', views.CritiqueGolden, name='CritiqueGolden'),
    path('main/firstsemester/Critique/ACritique/CritiqueGoldenM/CritiqueGoldenAdd', views.CritiqueGoldenAdd, name='CritiqueGoldenAdd'),
    path('main/firstsemester/Critique/ACritique/CritiqueGoldenM/CritiqueGoldenE', views.CritiqueGoldenE, name='CritiqueGoldenE'),
    path('main/firstsemester/Critique/ACritique/CritiquePriveosS', views.CritiquePriveosS, name='CritiquePriveosS'),
    path('main/firstsemester/Critique/ACritique/CritiquePriveosS/CritiquePriveosAdd', views.CritiquePriveosAdd, name='CritiquePriveosAdd'),
    path('main/firstsemester/Critique/ACritique/CritiquePriveosS/CritiquePriveosM/<int:ExNo>/<int:semestery>', views.CritiquePriveosM,name='CritiquePriveosM'),
    path('main/firstsemester/Critique/ACritique/CritiquePriveosS/CritiquePriveos/<int:ExNo>/<int:semestery>', views.CritiquePriveos,name='CritiquePriveos'),
    
    path('main/firstsemester/History3/AHistory3', views.AHistory3, name='AHistory3'),
    path('main/firstsemester/History3/AHistory3/AHistory31M/AHistory31', views.AHistory31, name='AHistory31'),
    path('main/firstsemester/History3/AHistory3/AHistory31M/AHistory31E/<int:number>', views.AHistory31E, name='AHistory31E'),
    path('main/firstsemester/History3/AHistory3/History31M', views.AHistory31M, name='AHistory31M'),
    path('main/firstsemester/History3/AHistory3/AHistory34M', views.AHistory34M, name='AHistory34M'),
    path('main/firstsemester/History3/AHistory3/AHistory34M/AHistory34Add', views.AHistory34Add,name='AHistory34Add'),
    path('main/firstsemester/History3/AHistory3/AHistory34M/AHistory34E/<int:number>', views.AHistory34E,name='AHistory34E'),
    path('main/firstsemester/History3/AHistory3/AHistory34M/AHistory34/<int:number>', views.AHistory34,name='AHistory34'),
    path('main/firstsemester/History3/AHistory3/AHistory3GM', views.AHistory3GM, name='AHistory3GM'),
    path('main/firstsemester/History3/AHistory3/AHistory3GM/AHistory3G', views.AHistory3G, name='AHistory3G'),
    path('main/firstsemester/History3/AHistory3/AHistory3GM/AHistory3GE', views.AHistory3GE, name='AHistory3GE'),
    path('main/firstsemester/History3/AHistory3/AHistory3GM/AHistory3GAdd', views.AHistory3GAdd, name='AHistory3GAdd'),
    path('main/firstsemester/History3/AHistory3/AHistory3PS', views.AHistory3PS, name='AHistory3PS'),
    path('main/firstsemester/History3/AHistory3/AHistory3PS/AHistory3PAdd', views.AHistory3PAdd, name='AHistory3PAdd'),
    path('main/firstsemester/History3/AHistory3/AHistory3PS/AHistory3PM/<int:ExNo>/<int:semestery>', views.AHistory3PM, name='AHistory3PM'),
    path('main/firstsemester/History3/AHistory3/AHistory3PS/AHistory3P/<int:ExNo>/<int:semestery>', views.AHistory3P, name='AHistory3P'),

]