# Generated by Django 4.1.1 on 2022-11-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=500)),
                ('student_phone', models.CharField(max_length=500, unique=True)),
                ('student_balance', models.IntegerField(default=0)),
                ('activation_code', models.IntegerField(default=0)),
                ('device_id', models.CharField(default='0', max_length=500, unique=True)),
            ],
        ),
    ]
