# Generated by Django 4.1.1 on 2022-10-17 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_rename_student_fname_student_student_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_Phone',
            new_name='student_phone',
        ),
    ]
